### ISSUE TITLE
X-XSS-Protection

### ISSUE THREAD

**Issue by noraj** [thomaspatzke/Burp-MissingScannerChecks#6]
X-XSS-Protection is deprecated and counter productive.

- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection
- https://owasp.org/www-project-secure-headers/#x-xss-protection

So it should either be suppressed or the check reversed to ensure it is not set.

**Comment by thomaspatzke** [comment]
Hi! Thanks for pointing this out! As I'm not working anymore in the WebAppSec area for years I don't maintain this project anymore. I will now retire it as archived project. Feel free to fork and do necessary changes on your own.
